#QT_QPA_PLATFORMTHEME  DEFAULT=qt6ct  OVERRIDE=qt6ct
#QT_PLATFORMTHEME  DEFAULT=qt6ct  OVERRIDE=qt6ct
#QT_PLATFORM_PLUGIN  DEFAULT=qt6ct  OVERRIDE=qt6ct

#QT_QPA_PLATFORMTHEME  DEFAULT=qt5ct  OVERRIDE=qt5ct
#QT_PLATFORMTHEME  DEFAULT=qt5ct  OVERRIDE=qt5ct
#QT_PLATFORM_PLUGIN  DEFAULT=qt5ct  OVERRIDE=qt5ct

#export QT_STYLE_OVERRIDE=kvantum
#export QT_QPA_PLATFORMTHEME=gnome

export QT_QPA_PLATFORMTHEME=qt6ct
export QT_QPA_PLATFORMTHEME=qt5ct
